version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      # - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "8010:80/tcp"
    environment:
      TZ: 'Europe/Berlin'
      WEBPASSWORD: "replaceMe" # <- Password used to access your admin page
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d' # Just use volumes because you dont need to edit the files
    # cap_add:
      # - NET_ADMIN # DHCP needs this
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`hole.domain`)"
      - "traefik.http.routers.pihole.entrypoints=http"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
    restart: unless-stopped
    
networks:
  default:
    name: traefik_default
    external: true