version: '2.4'

services:
    jellyfin:
      image: jellyfin/jellyfin
      container_name: 'jellyfin'
      user: 1000:1000
      group_add: 
        - '107' #render
        - '44' #video
      volumes:
        - /home/juli/docker/config/jellyfin:/config
        - /home/juli/storage/venus/cache:/cache
        - /home/juli/storage/venus/media:/media
      restart: always
      devices:
        - /dev/dri/card0:/dev/dri/card0
        # Add more
      labels:
        - 'traefik.enable=true'
        # Jellyfin HTTPS
        - 'traefik.http.routers.jellyfin.entryPoints=https'
        - 'traefik.http.routers.jellyfin.rule=Host(`jellyfin.domain`)'
        - 'traefik.http.routers.jellyfin.tls=true'
        - 'traefik.http.routers.jellyfin.tls.domains=jellyfin.domain'
        - 'traefik.http.routers.jellyfin.middlewares=jellyfin-mw'
        - 'traefik.http.services.jellyfin-ui.loadBalancer.server.port=8096'
        - 'traefik.http.services.jellyfin-ui.loadBalancer.passHostHeader=true'
        - 'traefik.http.routers.jellyfin.service=jellyfin-ui'
        # Jellyfin HTTP
        - 'traefik.http.routers.jellyfin-insecure.entryPoints=http'
        - 'traefik.http.routers.jellyfin-insecure.rule=Host(`jellyfin.domain`)'
        - 'traefik.http.routers.jellyfin-insecure.middlewares=jellyfin-insecure-mw'
        - 'traefik.http.middlewares.jellyfin-insecure-mw.redirectscheme.scheme=https'
        - 'traefik.http.middlewares.jellyfin-insecure-mw.redirectscheme.permanent=false'
        - 'traefik.http.routers.jellyfin-insecure.service=noop@internal'
        # Middleware
        - 'traefik.http.middlewares.jellyfin-mw.headers.customResponseHeaders.X-Robots-Tag=noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex'
        - 'traefik.http.middlewares.jellyfin-mw.headers.SSLRedirect=true'
        - 'traefik.http.middlewares.jellyfin-mw.headers.SSLHost=jellyfin.snowjuli.tech'
        - 'traefik.http.middlewares.jellyfin-mw.headers.SSLForceHost=true'
        - 'traefik.http.middlewares.jellyfin-mw.headers.STSSeconds=315360000'
        - 'traefik.http.middlewares.jellyfin-mw.headers.STSIncludeSubdomains=true'
        - 'traefik.http.middlewares.jellyfin-mw.headers.STSPreload=true'
        - 'traefik.http.middlewares.jellyfin-mw.headers.forceSTSHeader=true'
        - 'traefik.http.middlewares.jellyfin-mw.headers.frameDeny=true'
        - 'traefik.http.middlewares.jellyfin-mw.headers.contentTypeNosniff=true'
        - 'traefik.http.middlewares.jellyfin-mw.headers.browserXSSFilter=true'
        - "traefik.http.middlewares.jellyfin-mw.headers.customFrameOptionsValue='allow-from https://jellyfin.domain'"